version: '3'

services:
  app:
    image: jdobreck/centuria-hub:latest
    build: .
    container_name: centuria-hub_app
    volumes:
      - ./src:/var/www/centuria-hub
    ports:
      - "8000:8000"
  nginx:
    image: nginx
    volumes:
      - ./src/nginx:/etc/nginx
    depends_on: 
      - app
    ports:
      - "80:80"
      - "443:443"